### ISSUE TITLE
Update requirements (install fail on dateutil)

### ISSUE THREAD

**Issue by martin-sicho** [seffnet/seffnet#26]
Got an error during installation

```python-traceback
(seffnet) sichom@sichom-Precision-T7600:~/projects/seffnet$ seffnet web
Traceback (most recent call last):
  File "/home/sichom/software/miniconda/envs/seffnet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 583, in _build_master
    ws.require(__requires__)
  File "/home/sichom/software/miniconda/envs/seffnet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 900, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/sichom/software/miniconda/envs/seffnet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.8.1 (/home/sichom/software/miniconda/envs/seffnet/lib/python3.7/site-packages), Requirement.parse('python-dateutil<2.8.1,>=2.1; python_version >= "2.7"'), {'botocore'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/sichom/software/miniconda/envs/seffnet/bin/seffnet", line 6, in <module>
    from pkg_resources import load_entry_point
  File "/home/sichom/software/miniconda/envs/seffnet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3251, in <module>
    @_call_aside
  File "/home/sichom/software/miniconda/envs/seffnet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3235, in _call_aside
    f(*args, **kwargs)
  File "/home/sichom/software/miniconda/envs/seffnet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 3264, in _initialize_master_working_set
    working_set = WorkingSet._build_master()
  File "/home/sichom/software/miniconda/envs/seffnet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 585, in _build_master
    return cls._build_from_requirements(__requires__)
  File "/home/sichom/software/miniconda/envs/seffnet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 598, in _build_from_requirements
    dists = ws.resolve(reqs, Environment())
  File "/home/sichom/software/miniconda/envs/seffnet/lib/python3.7/site-packages/pkg_resources/__init__.py", line 791, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (python-dateutil 2.8.1 (/home/sichom/software/miniconda/envs/seffnet/lib/python3.7/site-packages), Requirement.parse('python-dateutil<2.8.1,>=2.1; python_version >= "2.7"'), {'botocore'})

```

**Comment by ddomingof** [comment]
Hi @martin-sicho sorry for the delay. Which version of python are you using? Seffnet is conflicting with botocore in your python installation. Why dont you try to install it and run it on a virtual environment?

**Comment by martin-sicho** [comment]
Hi, no problem. It is *python 3.7.5* and the version of *botocore is 1.13.9.* I was installing this with @cthoyt to a vanilla conda environment (just python in it) with pip to try something. We eventually solved the problem by manually installing python-dateutil through pip. It's just it did not work out of the box and we ran into this error. Hence, this issue.

**Comment by cthoyt** [comment]
Sorry guys I have the solution but just haven’t sent the PR. Don’t worry
